/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.ufrsciencestech.panier.View;

import fr.ufrsciencestech.panier.Controler.Controleur;
import fr.ufrsciencestech.panier.Model.Panier;
import java.awt.BorderLayout;
import java.util.Observable;
import javax.swing.JButton;
import javax.swing.*;


/**
 *
 * @author di322945
 */
public class VueGraphiqueList extends javax.swing.JFrame implements VueGraphique {

    /**
     * Creates new form VueGraphiqueList
     */
    
    private JComboBox listeFruits;
    private JTextArea affiche;
    private JPanel pan;
    private final JButton inc;
    private final JButton dec;
    
    public VueGraphiqueList() {
        initComponents();
        
        listeFruits= new JComboBox();
        pan= new JPanel();
        affiche=new JTextArea();
        inc=new JButton("+");
        dec=new JButton("-");
        
        inc.setName("Plus");
        dec.setName("Moins");
        affiche.setName("Affiche");
        
        pan.add(inc);
        pan.add(listeFruits);
        
        add(pan, BorderLayout.NORTH);
        add(dec, BorderLayout.SOUTH);
        add(affiche, BorderLayout.CENTER);
        
        this.pack();
        this.setVisible(true);
        
    }

    public JButton getInc() {
        return inc;
    }

    public JButton getDec() {
        return dec;
    }

    public JComboBox getListeFruits() {
        return listeFruits;
    }

    public void setListeFruits(JComboBox listeFruits) {
        this.listeFruits = listeFruits;
    }

    public JTextArea getAffiche() {
        return affiche;
    }

    public void setAffiche(JTextArea affiche) {
        this.affiche = affiche;
    }

    public JPanel getPan() {
        return pan;
    }

    public void setPan(JPanel pan) {
        this.pan = pan;
    }
    
        @Override
    public void update(Observable m, Object o) {
        Panier p = (Panier) m;
        getAffiche().setText(((Integer)p.getFruits().size()).toString());
    }

    @Override
    public void addControleur(Controleur c) {
        getInc().addActionListener(c);
        getDec().addActionListener(c);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
**/
}
